export const GENERATE_TEAM = 'GENERATE_TEAM';

export const CHANGE_FORMATION = 'CHANGE_FORMATION';

export const GENERATE_SUBSTITUTES = 'GENERATE_SUBSTITUTES';
export const DONT_MAKE_SUBSTITUTE = 'DONT_MAKE_SUBSTITUTE';
export const MAKE_SUBSTITUTE = 'MAKE_SUBSTITUTE';
